apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mydockerwebapp
  labels:
    app: mydockerwebapp
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: mydockerwebapp
  template:
    metadata:
      labels:
        app: mydockerwebapp
    spec:
      containers:
        - name: mydockerwebapp
          image: ghadaj/mydockerwebapp:latest
          ports:
            - containerPort: 80
