apiVersion: v1
kind: Service
metadata:
  name: mydockerwebapp
  labels:
    app: mydockerwebapp
spec:
  type: LoadBalancer
  selector:
    app: mydockerwebapp
  ports:
    - port: 80
      targetPort: 80
