pipeline {
	agent any
	stages {
		stage('build and push docker image') {
		    steps {
    				docker.withRegistry('https://registry.hub.docker.com', 'dockerHub') {
					def customImage = docker.build("ghadaj/mydockerwebapp")
					customImage.push()
 				 
			}
		}
	 
	}
}
